ALTER TABLE users
ADD COLUMN IF NOT EXISTS provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';

ALTER TABLE evaluation_assignments
ADD COLUMN IF NOT EXISTS archived_by_evaluator BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE evaluation_assignments
ADD COLUMN IF NOT EXISTS archived_by_evaluatee BOOLEAN NOT NULL DEFAULT FALSE;
